version: "3.1"

services:
  ecobee-exporter:
      image: ecobee
      container_name: ecobee-exporter
      restart: always
      ports:
        - "9098:9098"
      volumes:
        - /mnt/user/appdata/ecobee-exporter/data:/db
      environment:
        ECOBEE_APPKEY: p3NbLx6iSYTjXDFHIMtM77SWWPLRuEZ0